def exploratory(data, ticker):
    print(f'Exploratory Data Analysis for {ticker}')
    print('Stock Data')
    print('-' * 60)
    print('Dataset information')
    print(data.info(memory_usage='deep'))
    print('-' * 60)
    print('Data shape:')
    print(data.shape)
    print('-' * 60)
    print("Data columns Names:")
    print(data.columns)
    print('-' * 60)
    print("Check for NaNs:")
    print(data.isnull().values.any())
    print('-' * 60)
    print("Data Statistics Summary:")
    print(data.describe())
